spring:
  main:
    web-application-type: none
    banner-mode: off
  output:
    ansi: 
      enabled: always


triptale:
  # Root directory for all trips (single git repo). Configurable.
  # Supports ~ for the user home directory.
  #data-dir: ~/.triptale
  data-dir: ~/Pictures/triptale-data
  git:
    # Default commit author (falls back to system git config if blank)
    author-name: ""
    author-email: ""

logging:
  level:
    root: INFO
    net.timafe.triptale: DEBUG
    org.eclipse.jgit: WARN
  pattern:
    console: "%d{HH:mm:ss} %-5level %logger{36} : %msg%n"
